export default {
    autoAllocateChunkSize: Symbol('autoAllocateChunkSize'),
    byobRequest: Symbol('byobRequest'),
    cancelAlgorithm: Symbol('cancelAlgorithm'),
    cancelSteps: Symbol('cancelSteps'),
    closeRequested: Symbol('closeRequested'),
    closedDefer: Symbol('closedDefer'),
    controller: Symbol('controller'),
    detached: Symbol('detached'),
    disturbed: Symbol('disturbed'),
    pendingPullIntos: Symbol('pendingPullIntos'),
    pullAgain: Symbol('pullAgain'),
    pullAlgorithm: Symbol('pullAlgorithm'),
    pulling: Symbol('pulling'),
    queue: Symbol('queue'),
    queueTotalSize: Symbol('queueTotalSize'),
    reader: Symbol('reader'),
    readIntoRequests: Symbol('readIntoRequests'),
    readRequests: Symbol('readRequests'),
    state: Symbol('state'),
    storedError: Symbol('storedError'),
    started: Symbol('started'),
    strategyHWM: Symbol('strategyHWM'),
    stream: Symbol('stream'),
    view: Symbol('view')
};
